# Generated by Django 5.1.6 on 2026-06-28 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursereview_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecontent',
            options={'ordering': ['course_id', 'order'], 'verbose_name': 'Konten Kelas', 'verbose_name_plural': 'Konten Kelas'},
        ),
    ]
