# Generated by Django 5.1.15 on 2026-07-03 07:19

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_content_article_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.lesson_pdf_upload_path, verbose_name='File PDF Materi'),
        ),
    ]
